export const BUTTON_TEXT = {
    SOLVE: 'SOLVE',
    CLEAR: 'CLEAR MAZE SOLUTION',
    RESET: 'RESET',
    INFO_PANEL: 'THE RAT IN A MAZE PROBLEM',
    GET_MAZE: 'USE PRE-GENERATED MAZE'
}

export const DISPATCH = {
    CLEAR_MAZE_SOLUTION: 'CLEAR_MAZE_SOLUTION',
    RESTART_MAZE: 'RESTART_MAZE',
    SET_SQUARE_TYPE: 'SET_SQUARE_TYPE',
    SET_IS_ROUTE: 'SET_IS_ROUTE'
}